// Package alerts manages in-app notifications generated by the budget service.
//
// Alerts are created automatically as a side-effect of budget progress checks:
//   - "budget_warning"  — fired when spending crosses the 80 % threshold.
//   - "budget_exceeded" — fired when spending equals or exceeds the limit.
//
// The alerts service also implements the budgets.AlertCreator interface so that
// the budgets package can trigger alert creation without creating an import cycle.
//
// Layer responsibilities:
//
//	model.go      — GORM struct, AlertType enum, request/response types
//	repository.go — database queries (list, mark-read, deduplication check)
//	service.go    — business logic + budgets.AlertCreator implementation
//	handler.go    — HTTP handlers wired to Gin routes with Swagger annotations
package alerts
